---
# defaults file for all.openvpn

openvpn_version: 2.3.11
openvpn_server_name: client

openvpn_service_name: openvpn
openvpn_user: nobody
openvpn_group: nobody

openvpn_static: false

openvpn_auth_enable: false

openvpn_client_endpoint: 10.8.0.2
openvpn_server_endpoint: 10.8.0.1
openvpn_client_ifconfig: "{{ openvpn_client_endpoint }} {{ openvpn_server_endpoint }}"

openvpn_client_pull: false
openvpn_pull: false
openvpn_dev: tun
openvpn_comp_lzo: true
openvpn_daemon: true
openvpn_keepalive: '10 60'
openvpn_nobind: true
openvpn_ns_cert_type: ''
openvpn_persist_key: true
openvpn_persist_tun: true
openvpn_ping_timer_rem: true
openvpn_proto: udp
openvpn_redirect_gateway: false
openvpn_remote_host: ''
openvpn_remote_port: 1194
openvpn_remote_proto: "{{ openvpn_proto }}"
openvpn_resolv_retry: infinite
openvpn_status: openvpn-status.log
openvpn_verb: 3

openvpn_ca_certificate: ''
openvpn_client_certificate: ''
openvpn_client_key: ''
openvpn_dh2048: ''
